### PR TITLE
Update make_variations_v2.py

### PR DESCRIPTION
**Pull request by robinhood2014**
Added a section for Sean Hannity, plus cleaned up some hastily written code.

### CODE REVIEW

**Comment by robinhood2014** [comment]
I don't know what's wrong. The extension will not add Hannity to its list of actions.

**Comment by djacobow** [comment]
the insults are not packaged with the extension. The are loaded separately
from my server, so that I can add to them without updating the extension.

Let me take a look at them I'll update them if they're ok.

**Comment by djacobow** [comment]
I just uploaded the insults based on your changes. If you open the
extension and click "save" next to the insults url (or move the clean/dirty
dropdown), it should reload and you should start seeing hannity insults.

Thanks for the file cleanup. If you mark your PR as ready to submit, I can
merge it. Or, if you want I can just take the file changes directly and use
that. In the latter case, you won't get "credit.".

Best,
Dave J

**Comment by djacobow** [comment]
[image: image.png]

**Comment by robinhood2014** [comment]
Okay, I'll do that.

Also, I've got another name to add to the list -- Mark Zuckerberg. He seems to support Trump's rage against social media platforms. I'll create another branch and think of some insults for him.

Brandon Taylor
________________________________

**Comment by djacobow** [comment]
Ok, merged. If you want to continue to edit that file and make new commits,
I think you can do it from that same branch. You could also just send me
the file, if you'd rather.

I feel like Zuck and Jack Dorsey both need the treatment, but it's hard to
come up with a bunch to cover them each.

Best,
-- dave j

**Pull request merged**
